require('dotenv').config();
const express = require('express');
const cors = require('cors');
const nodemailer = require('nodemailer');
const bcrypt = require('bcrypt');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const db = require('./database');
const jwt = require('jsonwebtoken');
const { v4: uuidv4 } = require('uuid');

function authenticateToken(req, res, next) {
  const token = req.headers['authorization']?.split(' ')[1];
  if (!token) return res.status(401).json({ error: 'Unauthorized' });
  jwt.verify(token, process.env.JWT_SECRET, (err, u) => {
    if (err) return res.status(403).json({ error: 'Forbidden' });
    if (req.params.userId && req.params.userId !== u.userId) {
       return res.status(403).json({ error: 'Forbidden access to other user' });
    }
    req.user = u;
    next();
  });
}

const app = express();
app.use(cors());
app.use(express.json());

// ─── HEALTHCHECK ROUTE (For Vercel Keep-Awake Pinger) ──────────────────────
app.get('/', (req, res) => {
  res.status(200).send('CycleSync Backend is alive and evaluating schedules! 🌸');
});

const PORT = process.env.PORT || 3000;
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    user: process.env.SMTP_EMAIL,
    pass: process.env.SMTP_APP_PASSWORD,
  },
  connectionTimeout: 10000, 
});

const otpStore = {};

// ─── AUTHENTICATION ROUTES ───────────────────────────────────────────────────
app.post('/api/auth/send-otp', async (req, res) => {
  const { email } = req.body;
  if (!email) return res.status(400).json({ error: 'Email is required' });

  const otp = Math.floor(100000 + Math.random() * 900000).toString();
  otpStore[email] = { otp, expires: Date.now() + 10 * 60 * 1000 };

  const mailOptions = {
    from: process.env.SMTP_EMAIL,
    to: email,
    subject: 'Your CycleSync Verification Code',
    text: `Your OTP for verification is: ${otp}`,
    html: `
      <div style="font-family: Arial, sans-serif; background: #fff0f3; padding: 40px 20px; text-align: center;">
        <div style="background: white; max-width: 480px; margin: 0 auto; padding: 40px 24px; border-radius: 24px; box-shadow: 0 8px 24px rgba(232,121,160,0.15);">
          <div style="font-size: 48px; margin-bottom: 12px;">🌸</div>
          <h1 style="color: #e879a0; margin: 0 0 8px; font-size: 26px;">CycleSync</h1>
          <p style="color: #9b6b8a; font-size: 16px; margin: 0 auto 30px;">
            Here is your unique verification code. It is valid for 10 minutes.
          </p>
          <div style="background: #fdf2f8; padding: 24px; border-radius: 16px; display: inline-block; border: 2px solid #fce7f3;">
            <h2 style="margin: 0; font-size: 48px; letter-spacing: 12px; color: #a855f7;">${otp}</h2>
          </div>
          <p style="color: #d1b8c8; font-size: 13px; margin-top: 30px;">
            Securely generated by your CycleSync App. If you didn't request this, ignore this email.
          </p>
        </div>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    res.json({ message: 'OTP sent successfully!' });
  } catch (error) {
    console.error('SMTP error:', error.message || error);
    res.status(500).json({ error: 'Failed to send OTP email' });
  }
});

app.post('/api/auth/register', async (req, res) => {
  const { name, dob, email, mobile, password, otp } = req.body;
  
  if (email && otp) {
    const record = otpStore[email];
    if (!record || record.otp !== otp || record.expires < Date.now()) {
      return res.status(400).json({ error: 'Invalid or expired OTP' });
    }
    delete otpStore[email];
  }

  try {
    const hashedPw = await bcrypt.hash(password, 10);
    const id = uuidv4();
    const createdAt = new Date().toISOString();

    db.run(
      `INSERT INTO users (id, name, dob, email, mobile, password_hash, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [id, name, dob, email, mobile, hashedPw, createdAt],
      function (err) {
        if (err) return res.status(400).json({ error: 'Email already exists or DB error' });
        const user = { id, name, dob, email, mobile, gender: 'female', createdAt };
        const token = jwt.sign({ userId: id }, process.env.JWT_SECRET, { expiresIn: '30d' });
        res.json({ user, token });
      }
    );
  } catch (err) {
    res.status(500).json({ error: 'Registration failed' });
  }
});

app.post('/api/auth/login', async (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) return res.status(400).json({ error: 'Email and password required' });

  db.get(`SELECT * FROM users WHERE email = ?`, [email], async (err, user) => {
    if (err || !user) return res.status(400).json({ error: 'Invalid email or user not found' });
    
    const valid = await bcrypt.compare(password, user.password_hash);
    if (!valid) return res.status(400).json({ error: 'Invalid password' });
    
    const token = jwt.sign({ userId: user.id }, process.env.JWT_SECRET, { expiresIn: '30d' });
    return res.json({ user, token });
  });
});

// ─── RESET PASSWORD ROUTES ─────────────────────────────────────────────────────
app.post('/api/auth/forgot-password-otp', (req, res) => {
  const { email } = req.body;
  
  db.get(`SELECT * FROM users WHERE email = ?`, [email], async (err, user) => {
    if (err || !user) return res.status(404).json({ error: 'No account found with this email' });

    const otp = Math.floor(100000 + Math.random() * 900000).toString();
    otpStore[email] = { otp, expires: Date.now() + 10 * 60 * 1000 };

    const mailOptions = {
      from: process.env.SMTP_EMAIL,
      to: email,
      subject: 'CycleSync Password Reset Request',
      html: `
        <div style="font-family: Arial, sans-serif; background: #fff0f3; padding: 40px 20px; text-align: center;">
          <div style="background: white; max-width: 480px; margin: 0 auto; padding: 40px 24px; border-radius: 24px; box-shadow: 0 8px 24px rgba(232,121,160,0.15);">
            <div style="font-size: 48px; margin-bottom: 12px;">🔐</div>
            <h1 style="color: #e879a0; margin: 0 0 8px; font-size: 26px;">CycleSync</h1>
            <p style="color: #9b6b8a; font-size: 16px; margin: 0 auto 30px;">
              You requested a password reset. Here is your temporary reset code. It is valid for 10 minutes.
            </p>
            <div style="background: #fdf2f8; padding: 24px; border-radius: 16px; display: inline-block; border: 2px solid #fce7f3;">
              <h2 style="margin: 0; font-size: 48px; letter-spacing: 12px; color: #a855f7;">${otp}</h2>
            </div>
            <p style="color: #d1b8c8; font-size: 13px; margin-top: 30px;">
              If you didn't request a password reset, please ignore this email and your password will remain untouched.
            </p>
          </div>
        </div>
      `,
    };

    try {
      await transporter.sendMail(mailOptions);
      res.json({ message: 'Reset OTP sent successfully!' });
    } catch (error) {
      console.error('SMTP error:', error.message || error);
      res.status(500).json({ error: 'Failed to send reset email' });
    }
  });
});

app.post('/api/auth/reset-password', async (req, res) => {
  const { email, otp, newPassword } = req.body;
  const record = otpStore[email];
  
  if (!record || record.otp !== otp || record.expires < Date.now()) {
    return res.status(400).json({ error: 'Invalid or expired OTP' });
  }

  try {
    const hashedPw = await bcrypt.hash(newPassword, 10);
    db.run(`UPDATE users SET password_hash = ? WHERE email = ?`, [hashedPw, email], function(err) {
      if (err) return res.status(500).json({ error: 'Database update failed' });
      delete otpStore[email];
      res.json({ success: true });
    });
  } catch(e) {
    res.status(500).json({ error: 'Failed to reset password' });
  }
});

// ─── LOGS ROUTES ─────────────────────────────────────────────────────────────
app.get('/api/logs/:userId', authenticateToken, (req, res) => {
  db.all(`SELECT * FROM logs WHERE user_id = ? ORDER BY date ASC`, [req.params.userId], (err, rows) => {
    if (err) return res.status(500).json({ error: 'DB Error' });
    const formatted = rows.map(r => ({ ...r, symptoms: JSON.parse(r.symptoms || '[]') }));
    res.json(formatted);
  });
});

app.get('/api/log/:userId/:date', authenticateToken, (req, res) => {
  db.get(`SELECT * FROM logs WHERE user_id = ? AND date = ?`, [req.params.userId, req.params.date], (err, row) => {
    if (err || !row) return res.json(null);
    res.json({ ...row, symptoms: JSON.parse(row.symptoms || '[]') });
  });
});

app.post('/api/logs/:userId', authenticateToken, (req, res) => {
  const { date, flowLevel, painLevel, moodLevel, symptoms, notes, bloodColor, clotting, energyLevel, discharge } = req.body;
  const userId = req.params.userId;
  const id = userId + "_" + date;
  const savedAt = new Date().toISOString();
  const symptomsJson = JSON.stringify(symptoms || []);

  db.run(
    `INSERT OR REPLACE INTO logs (id, user_id, date, flowLevel, painLevel, moodLevel, symptoms, notes, bloodColor, clotting, energyLevel, discharge, saved_at) 
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [id, userId, date, flowLevel, painLevel, moodLevel, symptomsJson, notes, bloodColor, clotting, energyLevel, discharge, savedAt],
    (err) => {
      if (err) { console.error(err); return res.status(500).json({ error: 'Failed to save log' }); }
      res.json({ success: true, id });
    }
  );
});

// ─── REMINDERS ROUTE ─────────────────────────────────────────────────────────
app.get('/api/reminders/:userId', authenticateToken, (req, res) => {
  db.get(`SELECT reminders FROM users WHERE id = ?`, [req.params.userId], (err, row) => {
    if (err || !row) return res.status(404).json({ error: 'User not found' });
    res.json({ reminders: row.reminders ? JSON.parse(row.reminders) : null });
  });
});

app.post('/api/reminders/:userId', authenticateToken, (req, res) => {
  const { reminders } = req.body;
  db.run(`UPDATE users SET reminders = ? WHERE id = ?`, [JSON.stringify(reminders), req.params.userId], function(err) {
    if (err) return res.status(500).json({ error: 'Failed to save reminders' });
    res.json({ success: true });
  });
});

// ─── AI ROUTE (GEMINI 2.5) ───────────────────────────────────────────────────
app.post('/api/ai/suggestion', async (req, res) => {
  const { prompt } = req.body;
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" }); 
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    res.json({ content: text });
  } catch (error) {
    console.error("Gemini Error:", error);
    try {
      const fallbackModel = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
      const result = await fallbackModel.generateContent(prompt);
      const text = result.response.text();
      res.json({ content: text });
    } catch(err2) {
      res.status(500).json({ error: 'Failed to generate AI content' });
    }
  }
});

// ─── REMINDERS TEST ROUTE ──────────────────────────────────────────────────────
const scheduler = require('./scheduler');
app.get('/api/test-reminders', (req, res) => {
  scheduler.triggerTest();
  res.json({ message: 'Triggered immediate cron evaluation sequence for all users.' });
});

app.get('/api/test/email/otp', (req, res) => {
  const otp = "123456";
  res.send(`
    <div style="font-family: Arial, sans-serif; background: #fff0f3; padding: 40px 20px; text-align: center; height: 100vh; margin: -8px;">
      <div style="background: white; max-width: 480px; margin: 0 auto; padding: 40px 24px; border-radius: 24px; box-shadow: 0 8px 24px rgba(232,121,160,0.15);">
        <div style="font-size: 48px; margin-bottom: 12px;">🌸</div>
        <h1 style="color: #e879a0; margin: 0 0 8px; font-size: 26px;">CycleSync</h1>
        <p style="color: #9b6b8a; font-size: 16px; margin: 0 auto 30px;">
          Here is your unique verification code. It is valid for 10 minutes.
        </p>
        <div style="background: #fdf2f8; padding: 24px; border-radius: 16px; display: inline-block; border: 2px solid #fce7f3;">
          <h2 style="margin: 0; font-size: 48px; letter-spacing: 12px; color: #a855f7;">${otp}</h2>
        </div>
        <p style="color: #d1b8c8; font-size: 13px; margin-top: 30px;">
          Securely generated by your CycleSync App. If you didn't request this, ignore this email.
        </p>
      </div>
    </div>
  `);
});

app.get('/api/test/email/reminder', (req, res) => {
  const reminder = { label: "Hydration reminder", icon: "💧" };
  res.send(`
    <div style="font-family: Arial, sans-serif; background: #fff0f3; padding: 40px 20px; text-align: center; height: 100vh; margin: -8px;">
      <div style="background: white; max-width: 480px; margin: 0 auto; padding: 40px 24px; border-radius: 24px; box-shadow: 0 8px 24px rgba(232,121,160,0.15);">
        <div style="font-size: 48px; margin-bottom: 12px;">${reminder.icon}</div>
        <h1 style="color: #e879a0; margin: 0 0 8px; font-size: 26px;">CycleSync</h1>
        <p style="color: #9b6b8a; font-size: 16px; margin: 0 auto 10px;">
          Here is your requested gentle reminder:
        </p>
        <div style="background: #fdf2f8; padding: 24px; border-radius: 16px; display: inline-block; border: 2px solid #fce7f3; margin-top: 10px;">
          <h2 style="margin: 0; font-size: 24px; color: #a855f7; font-weight: 700;">${reminder.label}</h2>
        </div>
        <p style="color: #d1b8c8; font-size: 13px; margin-top: 30px;">
          You can manage these reminders anytime in your CycleSync App settings.
        </p>
      </div>
    </div>
  `);
});

app.listen(PORT, () => console.log(`CycleSync API server running on port ${PORT}`));
